sudo: false

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      language: scala
      scala:
        - 2.11.12
      before_install:
        - docker pull daunnc/pdal:1.7.1
      services:
        - docker

    - os: linux
      jdk: oraclejdk8
      language: scala
      scala:
        - 2.12.5
      before_install:
        - docker pull daunnc/pdal:1.7.1
      services:
        - docker

    - os: osx
      scala:
        - 2.11.12
      compiler:
        - gcc
        - clang
      before_install:
        - brew update
        - brew install pdal || true # to make travis happy

    - os: osx
      scala:
        - 2.12.5
      compiler:
        - gcc
        - clang
      before_install:
        - brew update
        - brew install pdal || true # to make travis happy

addons:
  hostname: localhost

cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt

script:
  - .travis/run.sh

notifications:
  email:
    recipients:
      - gr.pomadchin@gmail.com
