sudo: false
before_install:
  - docker pull daunnc/pdal:1.7.1
language: scala
addons:
  hostname: localhost
services:
  - docker
jdk:
  - oraclejdk8
scala:
  - 2.11.12
  - 2.12.5
cache:
  directories:
   - $HOME/.ivy2
   - $HOME/.sbt
script:
  - docker run -it --net=host -v $HOME/.ivy2:/root/.ivy2 -v $HOME/.sbt:/root/.sbt -v $TRAVIS_BUILD_DIR:/pdal-java -e TRAVIS_SCALA_VERSION=$TRAVIS_SCALA_VERSION -e TRAVIS_COMMIT=$TRAVIS_COMMIT -e TRAVIS_JDK_VERSION=$TRAVIS_JDK_VERSION daunnc/pdal:1.7.1 /bin/bash -c "cd /pdal-java; .travis/test-all.sh"
notifications:
  email:
    recipients:
      - gr.pomadchin@gmail.com
